### ISSUE TITLE
Update Monitoring to Report RDS State Changes to SNS

### ISSUE THREAD

**Issue by rwc** [chef-customers/aws_native_chef_server#30]
**Background**: 

- Customer RDS state change occurred that broke replication between primary instance and read-only replica
- Primary RDS began storing large amounts of transaction/binary/WAL logs locally as replication wasn't occurring
- Customer upped storage size to accommodate for further accumulating logs, further breaking replication and exacerbating issue

**Request**:

- Update AWS Native Chef Server Cloudwatch monitoring to report RDS state changes + replica health to proper SNS topic. State changes (failovers primarily) are a known cause of replication issues between RDS instances

This will give the user of an AWS Native Chef Server the proper warning that something has gone sideways and corrective action may need to be taken.

[RDS Parameters to investigate](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Monitoring.html)
```
OldestReplicationSlotLag
ReplicaLag
```

[RDS Events to investigate](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html)
```
RDS-EVENT-0006 - The DB instance is restarting and will be unavailable until the restart is complete.
RDS-EVENT-0004 - The DB instance has shut down.
RDS-EVENT-0034 - Amazon RDS is not attempting a requested failover because a failover recently occurred on the DB instance.
RDS-EVENT-0013 - A Multi-AZ failover that resulted in the promotion of a standby instance has started.
RDS-EVENT-0015 - A Multi-AZ failover that resulted in the promotion of a standby instance is complete. It may take several minutes for the DNS to transfer to the new primary DB instance.
RDS-EVENT-0065 - The instance has recovered from a partial failover.
RDS-EVENT-0049 - A Multi-AZ failover has completed.
RDS-EVENT-0045 - An error has occurred in the read replication process. For more information, see the event message. For information on troubleshooting Read Replica errors, see Troubleshooting a MySQL or MariaDB Read Replica Problem.
RDS-EVENT-0057 - Replication on the Read Replica was terminated.
RDS-EVENT-0062 - Replication on the Read Replica was manually stopped
RDS-EVENT-0063 - Replication on the Read Replica was reset.
```

**Comment by irvingpop** [comment]
thanks @rwc - looks like it would be as simple as doing this:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-eventsubscription.html

theoretically we could start with all event types (getting more specific later based on operator feedback) and do something as simple as this:

```yaml
RdsEventSubscription: 
  Type: "AWS::RDS::EventSubscription"
  Properties: 
    SnsTopicArn: !Ref AlertNotificationTopic
    SourceIds: 
      - !Ref DBPostgres
    SourceType: "db-instance"
```

**Comment by rwc** [comment]
@irvingpop - Agreed. Adding the following code for `ReplicaLag` monitoring if we ever add a RO-Replica to this.

```
  RDSReplicaLag:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub RDSReplicaLag-${AWS::StackName}
      AlarmDescription: Alarm when RDS Replica Lag is greater than 3600s.
      AlarmActions: [!Ref AlertNotificationTopic]
      MetricName: ReplicaLag
      Namespace: AWS/RDS
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Average
      Threshold: 3600
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBPostgres
```
